=== MiryamKizilKurt/labs/src/main/webapp/WEB-INF/shop.xsd
<?xml version="1.0"?>



<xs:schema version="1.0"

           
    xmlns:xs="http://www.w3.org/2001/XMLSchema"          
    targetNamespace="http://www.xmllabs.com/labsshop"         
    xmlns="http://www.xmllab.com/labsshop"
    elementFormDefault="qualified">

 
   <xs:simpleType name="nameFormat">
        <xs:restriction base="xs:string">
        </xs:restriction>             
    </xs:simpleType>    



   <xs:simpleType name="titleFormat">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="cdsetFormat">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{1}" />
        </xs:restriction>
    </xs:simpleType>



   <xs:simpleType name="priceFormat">
        <xs:restriction base="xs:string">
        <xs:pattern value="\d{2}.\d{2}" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ratingFormat">
        <xs:restriction base="xs:string">
        <xs:pattern value="\d{1}" />
        </xs:restriction>
    </xs:simpleType>
    



   <xs:element name="shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movies" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="nameFormat" name="name"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    



   <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="titleFormat" name="title"/>                   
                            <xs:element type="cdsetFormat" name="cdset"/>
                            <xs:element type="price" name="price"/>
                            <xs:element type="ratingFormat" name="rating"/>                          
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MiryamKizilKurt/labs/target/labs-1.0-SNAPSHOT/WEB-INF/shop.xml
<shop xmlns="http://www.xmllabs.com/labsshop"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.xmllabs.com/labsshop shop.xsd">



   <name>Movie Land</name>



   <movies>



       <movie>



           <title>The Lord of the Rings</title>



           <cdset>3</cdset>



           <price>36.90</price>



           <rating>9</rating>



       </movie>



       <movie>



           <title>Mad Max</title>



           <cdset>4</cdset>



           <price>26.50</price>



           <rating>6</rating>



       </movie>



       <movie>



           <title>The Avengers</title>



           <cdset>3</cdset>



           <price>60.00</price>



           <rating>9</rating>



       </movie>



       <movie>



           <title>American Pie</title>



           <cdset>8</cdset>



           <price>102.00</price>



           <rating>8</rating>



       </movie>



       <movie>



           <title>Die Hard</title>



           <cdset>5</cdset>



           <price>32.50</price>



           <rating>5</rating>



       </movie>



   </movies>
   </shop>
